### ISSUE TITLE
从后往前匹配失败

### ISSUE THREAD

**Issue by DuWen** [hxicoder/DBDemo#2]
你好，在使用simple时，遇到了个问题，如下：
示例：aaaaamm
关键字：mm
结果：0

期待你的回复，thanks

**Comment by wangfenjin** [comment]
Related to https://github.com/wangfenjin/simple/issues/101

**Comment by hxicoder** [comment]
> Related to [wangfenjin/simple#101](https://github.com/wangfenjin/simple/issues/101)

👍

@DuWen 微信好像也是如此

**Comment by hxicoder** [comment]
> 你好，在使用simple时，遇到了个问题，如下： 示例：aaaaamm 关键字：mm 结果：0
> 
> 期待你的回复，thanks

分词规则如此，看了下微信、飞书、钉钉也有这种现象，可以参考一下大佬的文章https://www.wangfenjin.com/posts/simple-tokenizer/

**Comment by DuWen** [comment]
好的 感谢
